  - name: Copy rabbitmq repo to the remote server.
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: Install RabbitMQ
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

  - name: start and enable rabbitmq server service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create and provide permissions to the useer
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      state: present    