#jinja 2 templating
- name: copy {{component }} service to /etc/systemd/system/{{component }}.service
  ansible.builtin.template:
    src: "{{component }}.service.j2"
    dest: "/etc/systemd/system/{{component }}.service"
  notify: daemon reload #asking to execute

# creating a task in handlers/main,yaml - daemon-reload

#systemctl daemon reload
# - name: daemon reload enable and start
#   ansible.builtin.systemd_service:
#     name: catalogue
#     enabled: true
#     state: started
#     daemon_reload: true

#--------

# If this file - /etc/systemd/system/catalogue.service chnages then only need to reload otherwose no need which brings the need for handlers folder

- name: Start the service
  ansible.builtin.service:
    name: "{{component }}"
    state: restarted
    enabled: yes
