---
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: node-js_setup.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
